---
all:
  hosts:
    elk-instance:
      ansible_host: 51.250.88.29
      local_ip: 10.128.0.12
  vars:
    ansible_connection: ssh
    ansible_user: rkhozyainov

elk-instance:
  hosts:
    elk-instance:
